services:
  - type: web
    name: outlaws-heists-fe
    runtime: static
    buildCommand: yarn install && yarn build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
